### ISSUE TITLE
X: Cannot decode %s traces payload: %v [v0.4 read tcp 127.0.0.1:8126->127.0.0.1:37608: i/o timeout]

### ISSUE THREAD

**Issue by zomgbre** [DataDog/datadog-lambda-js#314] opened 2022-10-18 17:00 UTC
## Expected Behavior
No weird errors/warnings in the lambda log output.

## Actual Behavior
Lambda log output on occasion:
"X: Cannot decode %s traces payload: %v [v0.4 read tcp 127.0.0.1:8126->127.0.0.1:37608: i/o timeout"

## Steps to Reproduce the Problem

  1. Use CDK to add Datadog layer to a lambda with below configuration:
  ```
   this._datadog = new Datadog(this, 'Datadog', {
            env: 'test',
            service: 'test',
            version: '2022-10-17t17:58:40.514z',
            nodeLayerVersion: 84,
            extensionLayerVersion: 29,
            captureLambdaPayload: true,
            apiKeySecretArn: `arn:aws:secretsmanager:${Stack.of(this).region}:${Stack.of(this).account}:secret:xxx/datadog`
        });
  ```
  2. Deploy lambda.
  3. Send requests to the lambda until this error is seen. (I'm not exactly sure what is causing it...)

## Specifications

  - Datadog Lambda Layer version: 29
  - Node version: 84

## Stacktrace

  ```
 X: Cannot decode %s traces payload: %v [v0.4 read tcp 127.0.0.1:8126->127.0.0.1:37608: i/o timeout
  ```

**Comment by tianchu** [comment] 2022-10-25 20:11
@zomgbre Thank you for flagging this issue, we are looking into the root cause.

**Comment by astuyve** [comment] 2023-02-15 21:08
Hi, a fix for this has been in the most recent versions of the Datadog extension for some time. Please upgrade to the latest (37) and feel free to re-open if this is still an issue.

Thanks!

**Closed by astuyve** 2023-02-15 21:08 UTC
