### ISSUE TITLE
ESModule support failure due to `require`-ing our client code

### ISSUE THREAD

**Issue by paco-sparta** [DataDog/datadog-lambda-js#295] opened 2022-07-20 13:05 UTC
## Expected Behavior
Pointing the CMD to `handler.handle.mjs` should make the lambda compatible with ESModules.

## Actual Behavior

When launching our handler with package.json specifying "modules" and pointing our Docker file to "handler.handle.mjs", we see a `require` error at runtime.

```
2022-07-20T12:09:01.317Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "require() of ES Module /var/task/app.js from /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js not supported.\nInstead change the require of app.js in /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js to a dynamic import() which is available in all CommonJS modules.",
    "code": "ERR_REQUIRE_ESM",
    "stack": [
        "Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/app.js from /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js not supported.",
        "Instead change the require of app.js in /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js to a dynamic import() which is available in all CommonJS modules.",
        "    at Module.Hook.Module.require (/var/task/node_modules/dd-trace/packages/dd-trace/src/ritm.js:72:33)",
        "    at _tryRequireSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:248:12)",
        "    at _loadUserAppSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:286:16)",
        "    at loadSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:374:19)",
        "    at Object.<anonymous> (/var/task/node_modules/datadog-lambda-js/dist/handler.js:35:27)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:857:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:907:25)",
        "    at _loadUserApp (file:///var/runtime/index.mjs:933:22)",
        "    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:964:27)",
        "    at start (file:///var/runtime/index.mjs:1124:42)",
        "    at file:///var/runtime/index.mjs:1130:7",
        "    at async Promise.all (index 0)"
    ]
}
```

Where `app.js` is our client code, transpiled to ES2020 using `tsc` with `esmoduleinterop` and `isolatedModules` enabled. Node is configured to use experimental `node` resolution for imports so file extensions aren't needed.

## Steps to Reproduce the Problem

  1. Create a new Docker-based nodejs project with datadog. Use TSC to compile with configurations above.
  1. Point Docker to CMD ["node_modules/datadog-lambda-js/dist/handler.handler.mjs"]
  1. Deploy with serverless
  2. See error above

## Specifications

  - Datadog NPM version: 6.81.X
  - Node version: 16.X

## Stacktrace

  ```
2022-07-20T12:09:01.317Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "require() of ES Module /var/task/app.js from /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js not supported.\nInstead change the require of app.js in /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js to a dynamic import() which is available in all CommonJS modules.",
    "code": "ERR_REQUIRE_ESM",
    "stack": [
        "Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/app.js from /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js not supported.",
        "Instead change the require of app.js in /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js to a dynamic import() which is available in all CommonJS modules.",
        "    at Module.Hook.Module.require (/var/task/node_modules/dd-trace/packages/dd-trace/src/ritm.js:72:33)",
        "    at _tryRequireSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:248:12)",
        "    at _loadUserAppSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:286:16)",
        "    at loadSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:374:19)",
        "    at Object.<anonymous> (/var/task/node_modules/datadog-lambda-js/dist/handler.js:35:27)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:857:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:907:25)",
        "    at _loadUserApp (file:///var/runtime/index.mjs:933:22)",
        "    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:964:27)",
        "    at start (file:///var/runtime/index.mjs:1124:42)",
        "    at file:///var/runtime/index.mjs:1130:7",
        "    at async Promise.all (index 0)"
    ]
}
  ```

**Comment by DarcyRaynerDD** [comment] 2022-07-20 15:40
Hi Paco, is there a package.json next to your app.js file, that specifies it's a ES module?
We try to replicate the logic AWS describes here with how we load modules, and a .js file will be interpreted as a common js file unless there is a package.json file next to it declaring the module type: https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/

**Comment by paco-sparta** [comment] 2022-07-21 09:15
I have added a handful of logs to a modified `node_modules`to follow the logic:

```
function _hasFolderPackageJsonTypeModule(folder) {
   ...
    var pj = path_1.default.join(folder, "/package.json");
    var pppp = fs_1.default.existsSync(pj);
    console.log(JSON.stringify({ path: pj, exists: pppp }));
```

Yields `{"path":"/var/task/package.json","exists":true}`, and a few lines later in

```
var pkg = JSON.parse(fs_1.default.readFileSync(pj, "utf-8"));
console.log(JSON.stringify({ pkg, hasModule: pkg.type === "module" }));
```

I see `{"pkg":{...}, "hasModule":true}`.

This means that
 
```
function _tryRequireSync(appRoot, moduleRoot, module) {
   ...

    // If package.json type != module, .js files are loaded via require.
    var pjHasModule = _hasPackageJsonTypeModule(lambdaStylePath);
    console.log(JSON.stringify({pjHasModule}));
    if (!pjHasModule) {
```

Returns `{"pjHasModule":true}` and the logic falls through to `require` at the end of the method, which causes the exception due to incompatibility:

```
{
    "errorType": "Error",
    "errorMessage": "require() of ES Module /var/task/app.js from /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js not supported.\nInstead change the require of app.js in /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js to a dynamic import() which is available in all CommonJS modules.",
    "trace": [
        "Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/app.js from /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js not supported.",
        "Instead change the require of app.js in /var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js to a dynamic import() which is available in all CommonJS modules.",
        "    at Module.Hook.Module.require (/var/task/node_modules/dd-trace/packages/dd-trace/src/ritm.js:72:33)",
        "    at _tryRequireSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:252:12)",
        "    at _loadUserAppSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:290:16)",
        "    at loadSync (/var/task/node_modules/datadog-lambda-js/dist/runtime/user-function.js:378:19)",
        "    at Object.<anonymous> (/var/task/node_modules/datadog-lambda-js/dist/handler.js:35:27)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:857:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:907:25)",
        "    at _loadUserApp (file:///var/runtime/index.mjs:933:22)",
        "    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:964:27)",
        "    at start (file:///var/runtime/index.mjs:1124:42)",
        "    at file:///var/runtime/index.mjs:1130:7",
        "    at async Promise.all (index 0)"
    ]
}
```

**Comment by paco-sparta** [comment] 2022-07-21 09:16
Let me follow why `_tryRequire` falls through this path.

**Comment by paco-sparta** [comment] 2022-07-21 09:38
I have copied the contents of `.mjs` into `.js` and another WTF

```
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Cannot use import statement outside a module",
    "trace": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Cannot use import statement outside a module",
        "    at _loadUserApp (file:///var/runtime/index.mjs:936:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:964:21)",
        "    at async start (file:///var/runtime/index.mjs:1124:23)",
        "    at async file:///var/runtime/index.mjs:1130:1"
    ]
}
```

The enviro is not picking up that we're working with modules. What.

**Comment by paco-sparta** [comment] 2022-07-21 10:29
I have moved the whole repo to `mjs` and `mts` and still no result. I removed the node experimental resolver and still nothing.

```
FROM public.ecr.aws/lambda/nodejs:16

COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/extensions/ /opt/extensions

# Configure by --buildArgs
ENV DD_LAMBDA_HANDLER "app.handler"
ENV DD_SITE "datadoghq.eu"
ENV DD_API_KEY "66b951cc1b4ae09c2d79a9c8587970da"

COPY package.json ./
COPY package-lock.json ./

COPY lib ./ # contains a copy of node_modules

CMD ["node_modules/datadog-lambda-js/dist/handler.handler"]
```

I _know_ it's all there. I'm at my wits' end to force it to load the handler. The exception is already telling me that Lambda is using the mjs runtime `file:///var/runtime/index.mjs:1130:1`

Why why why

**Comment by DarcyRaynerDD** [comment] 2022-07-22 19:30
What happens if you change
```
CMD ["node_modules/datadog-lambda-js/dist/handler.handler"]
```
to
```
CMD ["node_modules/datadog-lambda-js/dist/handler.mjs.handler"]
```
The reason we have two files, is there is a cjs entry point for the node 12 runtime, (which doesn't support .mjs). If you use one of our lambda layers, we make sure node_modules/datadog-lambda-js/dist/handler.handler uses the right version for your runtime, but in the npm module we don't know which runtime you are using, so we leave both in. If this change does work, I will update our documentation to be cleared for Dockerfile users.

If that doesn't work, I think a productive next step would be to send us a zip with a minimum reproduction.

**Comment by paco-sparta** [comment] 2022-07-25 09:27
Your suggestion was helpful but didn't work :(

Here's the minimum repro I was able to put together:

[sparta-lambda-failure-example.zip](https://github.com/DataDog/datadog-lambda-js/files/9179843/sparta-lambda-failure-example.zip)

**Comment by bgeese-szdm** [comment] 2022-07-26 08:30
We have the same or a very similar issue. We client code in a container image with modules and no bundling or processing of the JavaScript at all. `package.json` specifies the type "module" and we have a simply `app.js` file that exports a handler. That worked fine until we integrated the datadog handler.

The Dockerfile is straightforward:
`
FROM public.ecr.aws/lambda/nodejs:14

ENV NODE_ENV=production
ENV DD_LAMBDA_HANDLER="app.handler"
ENV DD_TRACE_ENABLED="true"
ENV DD_FLUSH_TO_LOG="true"

# Install Chrome to get all of the dependencies installed
# ...

COPY .npmrc ${LAMBDA_TASK_ROOT}/
COPY package*.json ${LAMBDA_TASK_ROOT}/
COPY src ${LAMBDA_TASK_ROOT}

RUN npm install --production

RUN rm .npmrc

CMD ["node_modules/datadog-lambda-js/dist/handler.handler"]
`

When we change the CMD back to ["app.handler"], everything works.

**Comment by DarcyRaynerDD** [comment] 2022-07-26 20:27
@paco-sparta Thanks for the reproduction, it helps a lot. We will work on a fix for this soon.

**Comment by kimi-p** [comment] 2022-07-27 21:31
@paco-sparta @bgeese-szdm 
We found the issue is due to `node_modules/datadog-lambda-js/dist/handler.js` file exists (for node12) and the existence of the file will make `_tryRequire()` try to import commonJS first. The temporary workaround is to remove the file for now. And we will think about the layer and npm use cases and come up with a solution for the long term. Thank you both for letting us know the issue!

```
RUN rm node_modules/datadog-lambda-js/dist/handler.js
CMD ["node_modules/datadog-lambda-js/dist/handler.handler"]
```
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/47579703/181376000-4537b76d-8384-49ec-9eb9-a4bbffa29144.png">

**Comment by kimi-p** [comment] 2022-07-28 20:17
Closing this one now and we will remove this `handler.js` file later this year after AWS deprecates their support of Node 12. Thanks again for flagging!

**Closed by kimi-p** 2022-07-28 20:17 UTC

**Comment by pakoito** [comment] 2022-07-28 23:54
Thank you both for the help!
