### ISSUE TITLE
TypeError: handler is not a function

### ISSUE THREAD

**Issue by tedyu** [DataDog/datadog-lambda-js#431] opened 2023-11-08 14:37 UTC
## Expected Behavior
datadog-lambda-js functions correctly with node.js 18.

## Actual Behavior
```
TypeError: handler is not a function
anonymous at /opt/nodejs/node_modules/datadog-lambda-js/utils/handler.js, 150
Object.<anonymous> at /opt/nodejs/node_modules/datadog-lambda-js/index.js, 167
step at /opt/nodejs/node_modules/datadog-lambda-js/index.js, 44
Object.next at /opt/nodejs/node_modules/datadog-lambda-js/index.js, 25
anonymous at /opt/nodejs/node_modules/datadog-lambda-js/index.js, 19
new Promise at <anonymous>
__awaiter at /opt/nodejs/node_modules/datadog-lambda-js/index.js, 15
anonymous at /opt/nodejs/node_modules/datadog-lambda-js/index.js, 161
anonymous at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js, 94
anonymous at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js, 45
```

## Steps to Reproduce the Problem

  1. "datadog-lambda-js": ">=6.89.0"
  1. node.js 18
  1.

## Specifications

  - Datadog Lambda Layer version:
  - Node version: 18

## Stacktrace
See above.

**Comment by tedyu** [comment] 2023-11-08 15:18
Can you confirm this is correct for node 18 ?
 ```  layers = ["arn:aws:lambda:${var.region}:464622532012:layer:Datadog-Node18-x:98"]```
thanks

**Comment by tedyu** [comment] 2023-11-08 18:20
@astuyve the link you mentioned, https://docs.datadoghq.com/serverless/aws_lambda/installation/nodejs/?tab=datadogcli, doesn't mention using wrapper.
Can you confirm whether wrapper is needed ? If so, what should be corrected in the formation in my previous comment ?

thanks

**Comment by astuyve** [comment] 2023-11-08 18:47
Hi!
Sorry! Those are just the entrypoint for our installation instructions.
Please select the installation method for your IAC provider using the tabs. We support most tools such as terraform, serverless framework, Sam, CDK, etc. It's okay if you're not using the `datadogcli` method.

If you want to proceed with this via the custom instrumentation path, which is what it seems, you'll need to click the `custom` tab: https://docs.datadoghq.com/serverless/aws_lambda/installation/nodejs/?tab=custom

If you want to use the `custom` path but don't want to use the built-in handler redirection supported by this library, that's fine, you can wrap your function manually (as it seems you are attempting to do here).

That is linked further on the `custom` page: https://docs.datadoghq.com/serverless/guide/handler_wrapper/

You _may_ need to pass the implicit `context` argument manually. It looks like that may be missing from the code snippet you've added (and perhaps the docs, although it should be passed automatically by the lambda runtime):
```
async function handler(event, context) {
```
I'd probably suggest trying the default handler redirection though, which means you don't need to touch this library in your own codebase but that's up to you.

Is this error present in Lambda, or coming from a local emulator?

Thanks!

**Comment by tedyu** [comment] 2023-11-08 18:58
I am upgrading code from node.js 14 to 18. I want to transform current code first to see if the upgrade can go through.

When I specify the `context` parameter, I get:
```
/opt/app/lambda/index.js
  79:31  error  'context' is defined but never used  no-unused-vars
```
Can you tell me how `context` should be passed down to datadog ?

Thanks

**Comment by astuyve** [comment] 2023-11-08 19:06
Hi, the `context` object is passed by the runtime and documented by [Lambda here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html).

If your linter is complaining about it, maybe you can use `_context` as the variable name, or ignore the rule?

Thanks!

**Comment by tedyu** [comment] 2023-11-08 19:28
After suppressing the lint error, I still get:
```
     TypeError: Cannot set property 'done' of undefined
      at /opt/app/node_modules/datadog-lambda-js/dist/utils/handler.js:163:22
      at /opt/app/node_modules/datadog-lambda-js/dist/index.js:223:70
      at step (node_modules/datadog-lambda-js/dist/index.js:44:23)
      at Object.next (node_modules/datadog-lambda-js/dist/index.js:25:53)
      at /opt/app/node_modules/datadog-lambda-js/dist/index.js:19:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/datadog-lambda-js/dist/index.js:15:12)
      at traceListenerOnWrap (node_modules/datadog-lambda-js/dist/index.js:200:36)
      at /opt/app/node_modules/datadog-lambda-js/dist/index.js:246:91
```
It seems I need to find a way to pass down the context.

**Comment by astuyve** [comment] 2023-11-08 19:41
That path looks interesting, you're getting this error in Lambda, or coming from a local emulator?
Can you provide a minimal project which reproduces this?

Thanks!

**Comment by tedyu** [comment] 2023-11-08 19:45
The stack trace was copied from our circleci job which runs unit tests.
I will see if the reproduction can be isolated.
Meanwhile, it would be nice if someone can advise on passing `context` parameter.
Thanks

**Comment by astuyve** [comment] 2023-11-08 19:53
Ahhhh I see! Thanks for that!

I had asked earlier if this error was being raised inside Lambda, but it's not.
This is occurring within a unit test, but you're exercising all of the features of this library outside of Lambda, which won't work.

You'll need to stub this library when testing it outside of Lambda (much like you would stub any normal external dependency). This library isn't meant to be executed without Lambda runtime features being present (nor will it run effectively without being able to reach the datadog agent or forwarder).

This is also why we support wrapping handlers via non-code paths, so that your unit tests can still run without this library being present.

I'm closing this issue as it's not an issue with this codebase.

Thank you!

**Closed by astuyve** 2023-11-08 19:53 UTC

**Comment by tedyu** [comment] 2023-11-08 20:06
I did some search w.r.t. stubbing out datadog handler for unit testing but haven't found answer.

If you can provide some pointer, that would be nice.

**Comment by tedyu** [comment] 2023-11-08 20:25
@astuyve 
Another possibility is for `datadog-lambda-js` to regard the absence of `context` as indication that the lambda is not operating in normal cloud environment and return early.
This would make `datadog-lambda-js` more developer friendly.

What do you think ?

**Comment by astuyve** [comment] 2023-11-08 20:47
Hi, you'll want to read the documentation for whatever test running library you're using. Jest or Mocha are both popular and offer this ability. You can even see how we do this with jest in [this library](https://github.com/DataDog/datadog-lambda-js/blob/773abccf575cd12e3fe0147d4b241634b2eea5a7/src/trace/listener.spec.ts#L53).

This library isn't intended to be a development dependency, so we wouldn't even expect it to be installed outside of Lambda.

We would have to carefully consider how and where we'd return early here because we spy on the function entrance and exit, and it may be challenging to fully support a "disabled" mode.

Instead most users find they can stub this dependency easily and do so in their unit tests.
Thanks!
AJ

**Comment by tedyu** [comment] 2023-11-08 20:58
From https://github.com/DataDog/datadog-lambda-js, I see node 16 mentioned.
Can you confirm that node 18 is supported by 6.89 release ?

Thanks

**Comment by astuyve** [comment] 2023-11-08 22:05
Hi yes, we support node 18 as per the readme:
<img width="973" alt="image" src="https://github.com/DataDog/datadog-lambda-js/assets/1598537/0564571f-32f6-471f-897c-4b9da801499a">
and all recent releases: https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.99.0

**Comment by tedyu** [comment] 2023-11-09 05:17
@astuyve 
For `TypeError: Cannot set property 'done' of undefined`, there is no such error when handler is called within unit test using 4.68.0 of datadog-lambda-js .

```
const event = (records = [record()]) => {
  const transformRecord = (rec) => ({
    kinesis: {
      kinesisSchemaVersion: '1.0',
      data: base64JSON(rec)
    }
  });

  return {
    Records: records.map(transformRecord)
  };
};
...
        await handler(event());
```
I am digging into datadog-lambda-js to see how the context can be constructed and passed to the handler.
If you (or some datadog developer) can give me some pointer, that would be appreciated.
