### ISSUE TITLE
Support DD_API_KEY_SECRET_ARN

### ISSUE THREAD

**Issue by samuelAle** [DataDog/datadog-lambda-js#89] opened 2020-08-05 00:43 UTC
## Expected Behavior

I would expect there to be feature parity between the python & nodejs lambda layers.

https://pypi.org/project/datadog-lambda/

if I provide a SecretsManager ARN in a variable called `DD_API_KEY_SECRET_ARN`, the lambda layer should be able to use the credentials found within this resource.

## Actual Behavior

not implemented

**Comment by tianchu** [comment] 2020-08-05 01:45
@samuelAle do you need to submit custom metrics [synchronously](https://docs.datadoghq.com/integrations/amazon_lambda/?tab=nodejs#synchronous-vs-asynchronous-custom-metrics) from the lambda function (aka, without going through logs)? I'm asking, because that's the only case that you need to supply a Datadog API key on your Lambda function (see https://github.com/DataDog/datadog-lambda-js#dd_flush_to_log). Typically you only need to set the API key on the forwarder.

**Comment by samuelAle** [comment] 2020-08-05 17:47
Ah, I didn't read that. Thanks for pointing it out. 

I can use this work around. Though someone else might run into this issue without wanting to resort to using cloudwatch logs.

**Comment by nhinsch** [comment] 2020-08-05 20:07
Going to close this issue for now as we don't have immediate plans to implement this, and the issue is moot when using the Datadog Forwarder.

**Closed by nhinsch** 2020-08-05 20:07 UTC
