### ISSUE TITLE
Automatic trace id log injection doesn't work with pino

### ISSUE THREAD

**Issue by Ozzee** [DataDog/datadog-lambda-js#171] opened 2021-03-19 12:01 UTC
## Expected Behavior

The documentation states that the trace id should get automatically injected to the logs for correlation if one is using a supported log library. Pino is listed as a [supported library](https://docs.datadoghq.com/tracing/connect_logs_and_traces/nodejs/).

Log lines that show up in Datadog should have the trace tab enabled and showing the trace for that request.

## Actual Behavior

The START, REPORT and END log-lines that are automatically generated by AWS Lambda have the trace tab enabled and the trace showing, but any manually sent log lines from inside the function don't have any trace id associated with them.

## Steps to Reproduce the Problem

We use TypeScript and our logger module looks like this:
```
import * as pino from 'pino'
import { getConfig } from '../config'

const config = getConfig()

export const logger = pino({
  name: 'service-name',
  level: config.LOG_LEVEL,
  formatters: {
    level(level) {
      return { level }
    }
  }
})
```

It gets used like this:
```
import { logger } from '../utils/logger'
...
} catch (error) {
      logger.error(error, `Product error`)
      return null
    }
```

## Specifications

  - Datadog Lambda Layer version: 49
  - Node version: nodejs12.x
  - Lambdas written in TypeScript
  - Traces are being sent from the lambda and we can see those in the web console, but they are not linked to any log-lines
  - console.log gets the trace id

**Comment by amcdnl** [comment] 2021-06-17 14:29
I'm also experiencing this issue.

**Comment by maxday** [comment] 2021-07-12 15:49
Can you please share which version of Pino you are using ?

**Comment by jsumners** [comment] 2021-07-12 15:55
In my case, I am using `^6.1.0`.

**Comment by amcdnl** [comment] 2021-07-19 12:16
I'm not sure what i did but this somehow started working for me.

**Comment by tianchu** [comment] 2021-08-04 14:44
Here is my testing function using `pino@6.13.0`:

```js
const logger = require('pino')({
  name: 'pino-test',
  formatters: {
    level(level) {
      return { level }
    }
  }
})

exports.handler = async (event) => {
    logger.error({'user_id': 123}, 'Product error');
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
```

And the log generated in CloudWatch logs do have the corresponding dd attributes, like `trace_id`, `span_id`, etc.

```json
{
    "level": "error",
    "time": 1628087986861,
    "pid": 9,
    "hostname": "169.254.123.65",
    "name": "pino-test",
    "user_id": 123,
    "dd": {
        "trace_id": "6746675099437916279",
        "span_id": "6746675099437916279",
        "service": "tc-test-plugin",
        "version": "0.0.1",
        "env": "dev"
    },
    "msg": "Product error"
}
```

I'm going to close the issue since it seems no longer reproducible.

**Closed by tianchu** 2021-08-04 14:44 UTC
Labels: dd-to-triage

**Comment by Ozzee** [comment] 2021-08-12 04:13
Thank you for looking into this. We are still experiencing the problem. I suppose it most likely has something to do with webpack and/or TypeScript. I've tried disabling minification and using a config as similar as possible to the one you posted, but the log lines sent by Pino still don't get the dd-object. We'll keep using console.log for now and if I have time I'll try to create a minimal setup where this can be reproduced.

**Comment by cayter** [comment] 2022-03-27 07:21
> Here is my testing function using `pino@6.13.0`:
> 
> ```js
> const logger = require('pino')({
>   name: 'pino-test',
>   formatters: {
>     level(level) {
>       return { level }
>     }
>   }
> })
> 
> exports.handler = async (event) => {
>     logger.error({'user_id': 123}, 'Product error');
>     const response = {
>         statusCode: 200,
>         body: JSON.stringify('Hello from Lambda!'),
>     };
>     return response;
> };
> ```
> 
> And the log generated in CloudWatch logs do have the corresponding dd attributes, like `trace_id`, `span_id`, etc.
> 
> ```json
> {
>     "level": "error",
>     "time": 1628087986861,
>     "pid": 9,
>     "hostname": "169.254.123.65",
>     "name": "pino-test",
>     "user_id": 123,
>     "dd": {
>         "trace_id": "6746675099437916279",
>         "span_id": "6746675099437916279",
>         "service": "tc-test-plugin",
>         "version": "0.0.1",
>         "env": "dev"
>     },
>     "msg": "Product error"
> }
> ```
> 
> I'm going to close the issue since it seems no longer reproducible.

@tianchu This is also not working for me, does the library inject dd object locally as well? I have checked the logInject config is set to `true`, but I still don't see the `dd` object being injected locally and production. Does this only work with pino@6.x and not pino@7.x?
